# ベースイメージの設定
FROM ubuntu

# Nginxのインストール
RUN apt-get update && apt-get upgrade
RUN apt-get -y install nginx

# ポートの指定
EXPOSE 80

# Webコンテンツの配置
ONBUILD ADD website.tar /var/www/html/

# nginxの実行
CMD [ "nginx", "-g", "daemon off;" ]